### ISSUE TITLE
Auth: esp vs python code

### ISSUE THREAD

**Issue by arturgspb** [salrashid123/esp_docker#1]
Hello!

I study ESP and I have a question - why is authorization checked on the python server too? I assumed that ESP nginx could do this and send decoded headers to the server.

**Comment by salrashid123** [comment]
ah...just paranoia :)  I didn't have to at all (as you noted, its already done via sidecar).
the only other reason is if somone accesses it somehow directly w/o  goinv via ESP.

i do this check again even when i used IAP to verify the custom JWT that google's identity aware proxy sends over:

https://github.com/salrashid123/envoy_iap/blob/master/http_server.py#L25

**Comment by arturgspb** [comment]
Thanks a lot!

I am currently programming a gRPC + Transcoding service and I want to give REST api to clients, but with verification of authenticity by access token. At the same time for transcoding and authorization, I want to use ESP.

Everything is good in production, but on a local machine I need to run and configure a lot of things - a google project for tests, a service account, an ESP in docker. Have you encountered this? Is it possible to make it somehow easier?

**Comment by salrashid123** [comment]
I've never ran ```ESP``` w/o the full integration in place (svc_account, docker, openapi specs uploaded, etc).

however, the docs for esp describe running it locally though i've never done this (sems like similar complexity to set it up in this mode anyway)
 - https://github.com/cloudendpoints/esp/blob/master/doc/tutorial.md#running-esp

---

Just to note, ```envoy``` also provides [grpc_transcoding](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_filters/grpc_json_transcoder_filter) and [JWT authentication](https://github.com/salrashid123/envoy_iap/blob/master/envoy_google.yaml#L32) but also takes more config for you to setup and run

**Comment by arturgspb** [comment]
Thx!
